### PR TITLE
Add find image position function

### PR DESCRIPTION
**Pull request by Abel-csd**
1. Add find image position function since sometimes we just need the position and don't need to click it.
2. The function click_by_image has parameters "button='left', double_click= False" but not used. Update this function to implement.

### CODE REVIEW

**Comment by jieliu2000** [comment]
@Abel-csd is it possible to make the second parameter not only image path but also allow to be a PIL image? You can judge if the type is a str first

**Comment by jieliu2000** [comment]
I also would like to suggest that you add an optional parent PIL img parameter in find_image_position so that it can search a sub image in a larger parent image. If this parameter is not provided then we take a screenshot and use it as parent image. We can even add a dedicated find_image_on_screen method to invoke find_image_pisition with none parent image parameter

**Comment by Abel-csd** [comment]
Thanks for your suggestions, I've updated the code.

**Comment by jieliu2000** [comment]
For click_by_image, since you can only click on screen, it might be not necessary to have the parent image parameter

**Pull request merged**
